Repository theislab/scvelo, pull requests merged in 2021-06, with the labels that each got.

#491 Update ci.yml
  .github/workflows/ci.yml
Labels: CI

#492 Extend `pl.velocity_embedding_stream` with new arguments
  scvelo/plotting/velocity_embedding_stream.py
Labels: plotting

#505 Update `recover_dynamics` docs
  scvelo/tools/dynamical_model.py
Labels: docs
